"""add asset name and symbol

Revision ID: 2072f2c809cc
Revises: e7c53e71cfc8
Create Date: 2026-05-13 14:59:51.609273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2072f2c809cc'
down_revision: Union[str, None] = 'e7c53e71cfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_price_reactions', sa.Column('asset_name', sa.String(length=255), nullable=True))
    op.add_column('event_price_reactions', sa.Column('asset_symbol', sa.String(length=50), nullable=True))
    op.add_column('event_price_reactions', sa.Column('event_title', sa.String(length=255), nullable=True))
    op.add_column('event_price_reactions', sa.Column('event_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_price_reactions', 'event_description')
    op.drop_column('event_price_reactions', 'event_title')
    op.drop_column('event_price_reactions', 'asset_symbol')
    op.drop_column('event_price_reactions', 'asset_name')
    # ### end Alembic commands ###