"""initial_schema

Revision ID: e7c53e71cfc8
Revises: 
Create Date: 2026-05-13 14:47:43.706577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c53e71cfc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_asset_links', sa.Column('asset_name', sa.String(length=255), nullable=True))
    op.add_column('event_asset_links', sa.Column('asset_symbol', sa.String(length=50), nullable=True))
    op.add_column('event_asset_links', sa.Column('event_title', sa.String(length=255), nullable=True))
    op.add_column('event_asset_links', sa.Column('event_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_event_price_reactions_event_id'), 'event_price_reactions', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_price_reactions_event_id'), table_name='event_price_reactions')
    op.drop_column('event_asset_links', 'event_description')
    op.drop_column('event_asset_links', 'event_title')
    op.drop_column('event_asset_links', 'asset_symbol')
    op.drop_column('event_asset_links', 'asset_name')
    # ### end Alembic commands ###